import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { cookies } from 'next/headers';
import Image from 'next/image';
import Link from 'next/link';
import { redirect } from 'next/navigation';

import './globals.css';
import { useTranslation } from './i18n';
import { FALLBACK_LANGUAGE, LANGUAGES, Language } from './i18n/consts';

export const metadata: Metadata = {
  title: 'devonnuri.wiki',
  description: 'Generated by create next app',
};

export const texGyreTermes = localFont({
  src: [
    {
      path: './fonts/texgyretermes-regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/texgyretermes-bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/texgyretermes-italic.woff2',
      weight: '400',
      style: 'italic',
    },
    {
      path: './fonts/texgyretermes-bolditalic.woff2',
      weight: '700',
      style: 'italic',
    },
  ],
  variable: '--font-texgyretermes',
  display: 'swap',
});

export const koPubBatang = localFont({
  src: [
    {
      path: './fonts/KoPubBatang-Light.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/KoPubBatang-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/KoPubDotum-Light.woff2',
      weight: '400',
      style: 'italic',
    },
    {
      path: './fonts/KoPubDotum-Bold.woff2',
      weight: '700',
      style: 'italic',
    },
  ],
  variable: '--font-kopubbatang',
  display: 'swap',
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const lang = cookieStore.get('lang')?.value;

  if (!lang) {
    redirect(`/${FALLBACK_LANGUAGE}/main_page`);
  }

  const { t } = await useTranslation(lang as Language);

  return (
    <html>
      <body
        className={`md:px-3 ${texGyreTermes.variable} ${koPubBatang.variable}`}
      >
        <div className="w-[48rem] mx-auto my-0 px-8 pb-8 border border-black min-h-screen">
          <div className="flex items-center justify-center my-10">
            <Link href="./main_page">
              <Image
                src="/devonnuri-wiki.svg"
                alt="devonnuri.wiki"
                width="284"
                height="75"
              />
            </Link>
          </div>
          <div>
            <input
              className="w-full text-[1.375em] italic border rounded mx-0 my-2 px-2 py-[0.2rem] border-black"
              type="text"
              placeholder={t('search')}
            />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
